include:
  - _pages

title: Bryant Finney
subtitle: >-
  Full Stack | Consultant | DevOps | Cloud
description: >-
  This site provides some of my thoughts, passions, and professional history.

author:
  name: Bryant Finney
  bio: |
    From low-level firmware to cloud-native systems, research and development have given
    me a drive for the technical side.
  avatar: /assets/img/profile-cropped.png
  links:
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/bryant-finney/
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/bryant-finney
    - label: GitLab
      icon: fab fa-gitlab
      url: https://gitlab.com/bryant.finney
    - label: "Twitter"
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/bryant_witha_T

baseurl: /about
url: https://bryant-finney.github.io
github_username: bryant-finney
repository: bryant-finney/about
show_downloads: true

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - github-pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  resume:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: /me
    values:
      author_profile: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true

  # _resume
  - scope:
      path: ""
      type: resume
    values:
      layout: single
      author_profile: false

footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/bryant-finney/about
    - label: Sitemap
      icon: fa fa-sitemap
      url: /about/sitemap
