title: Bryant Finney
description: >-
  This site contains my technical thoughts, passions, and history.

baseurl: "/about"
url: "https://bryant-finney.github.io"
github_username: bryant-finney

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

theme: jekyll-theme-minimal
